[package]
name = "starlingmonkey"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[[bin]]
name = "starling"
path = "src/main.rs"
test = false

[features]
debugmozjs = ['libstarling/debugmozjs']
profilemozjs = ['js/profilemozjs']
jitspew = ['js/jitspew']
intl = ['js/intl']
node_compat = ["libstarling/node_compat"]

[dependencies]
clap.workspace = true
core-runtime.workspace = true
js.workspace = true
libstarling.workspace = true
wasip3.workspace = true
wpt-support.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tempfile = "3"

[lints]
workspace = true
