[package]
name = "web-file"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
core-runtime.workspace = true
encoding_rs.workspace = true
js.workspace = true
web-globals.workspace = true
web-streams.workspace = true

[dev-dependencies]
libstarling.workspace = true
tokio.workspace = true

[lints]
workspace = true
