[toolchain]
# Keep this in sync with the project workspace's channel.
channel = "1.96"

components = [
    "clippy",
    # For support/crown
    "llvm-tools",
    # For support/crown
    "rustc-dev",
    # For formatting
    "rustfmt",
]
profile = "minimal"
