[package]
name = "libstarling"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
# No unit tests; skip building the (SpiderMonkey-sized) lib test harness binary.
test = false

[features]
debugmozjs = ['js/debugmozjs', "cpp-builtins/debugmozjs"]

[dependencies]
core-runtime.workspace = true
js.workspace = true
url.workspace = true
web-globals.workspace = true
web-streams.workspace = true
web-url.workspace = true
web-url-pattern.workspace = true
cpp-builtins.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasip3.workspace = true

[lints]
workspace = true