/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

//! Lint for detecting bare `JS::Value` fields in GC-traced structs.
//!
//! A raw `Value` stored inside a `#[allow_unrooted_interior]` struct (the kind
//! generated by `#[jsclass]` / `#[webidl_interface]`) is traced via
//! `TraceNullableRoot`, which only works during the `NotActive`/`MarkRoots` GC
//! phases. Since these structs live inside SpiderMonkey reserved slots and are
//! traced during the full marking phase, the bare `Value` must be wrapped in
//! `Heap<Value>` (= `mozjs::jsapi::Heap<Value>` / `js::heap::Heap<Value>`)
//! which traces via `TraceEdge` — the correct function for heap-resident GC
//! pointers.
//!
//! Without `Heap<Value>`, GC stress (e.g. `JS_GC_ZEAL=2,1`) reliably triggers:
//! ```text
//! Assertion failure: trc->runtime()->gc.state() == State::NotActive ||
//!     trc->runtime()->gc.state() == State::MarkRoots
//! ```

use rustc_hir::{self as hir};
use rustc_lint::{LateContext, LateLintPass, Lint, LintContext, LintPass, LintStore};
use rustc_middle::ty;
use rustc_session::declare_tool_lint;
use rustc_span::symbol::Symbol;

use crate::common::match_def_path_suffix;
use crate::symbols;

declare_tool_lint! {
    pub crown::BARE_VALUE_IN_GC_STRUCT,
    Deny,
    "bare JS::Value in a GC-traced struct must be wrapped in Heap<Value>"
}

pub fn register(lint_store: &mut LintStore) {
    let symbols = Symbols::new();
    lint_store.register_lints(&[BARE_VALUE_IN_GC_STRUCT]);
    lint_store.register_late_pass(move |_| Box::new(BareValuePass::new(symbols.clone())));
}

pub(crate) struct BareValuePass {
    symbols: Symbols,
}

impl BareValuePass {
    pub(crate) fn new(symbols: Symbols) -> Self {
        Self { symbols }
    }
}

impl LintPass for BareValuePass {
    fn name(&self) -> &'static str {
        "BareValueInGcStruct"
    }

    fn get_lints(&self) -> Vec<&'static Lint> {
        vec![BARE_VALUE_IN_GC_STRUCT]
    }
}

/// Returns `true` if `ty` is `mozjs_sys::jsapi::JS::Value` (the raw
/// SpiderMonkey `JS::Value` struct).
fn is_bare_js_value(sym: &Symbols, cx: &LateContext<'_>, ty: ty::Ty<'_>) -> bool {
    if let ty::Adt(did, _) = ty.kind() {
        // The canonical definition lives in the generated bindings:
        //   mozjs_sys :: jsapi :: JS :: Value
        // Re-exported as mozjs::jsapi::Value and js::native::Value.
        // All resolve to the same DefId.
        //
        // We match the intra-crate path suffix so the check works both
        // against the real mozjs_sys crate and local mock modules in tests.
        return match_def_path_suffix(cx, did.did(), &[sym.jsapi, sym.JS, sym.Value]);
    }
    false
}

/// Recursively checks whether `ty` contains a bare `JS::Value` (directly
/// or inside `Vec<Value>`, `Option<Value>`, etc.).  Returns `true` if a
/// bare Value is found at any nesting depth.
fn contains_bare_value<'tcx>(sym: &Symbols, cx: &LateContext<'tcx>, ty: ty::Ty<'tcx>) -> bool {
    let mut walker = ty.walk();
    while let Some(generic_arg) = walker.next() {
        let t = match generic_arg.kind() {
            rustc_middle::ty::GenericArgKind::Type(t) => t,
            _ => {
                walker.skip_current_subtree();
                continue;
            },
        };
        match t.kind() {
            ty::Adt(did, _) => {
                if is_bare_js_value(sym, cx, t) {
                    return true;
                }
                // Don't recurse into Heap<Value> — that's the correct wrapper.
                if is_heap_wrapper(sym, cx, did.did()) {
                    walker.skip_current_subtree();
                    continue;
                }
                // Continue recursing into other ADTs (Vec<Value>, Option<Value>, etc.)
            },
            ty::Ref(..) | ty::RawPtr(..) | ty::FnDef(..) | ty::FnPtr(..) => {
                walker.skip_current_subtree();
                continue;
            },
            _ => {},
        }
    }
    false
}

/// Returns `true` if the def is `mozjs_sys::jsgc::Heap` (the barrier-aware
/// wrapper), so we don't flag `Heap<Value>` as a bare Value.
fn is_heap_wrapper(sym: &Symbols, cx: &LateContext<'_>, def_id: rustc_span::def_id::DefId) -> bool {
    match_def_path_suffix(cx, def_id, &[sym.jsgc, sym.Heap])
}

impl<'tcx> LateLintPass<'tcx> for BareValuePass {
    fn check_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx hir::Item) {
        let sym = &self.symbols;

        // Only check structs that are #[allow_unrooted_interior] — these are
        // the FooImpl types generated by #[jsclass] / #[webidl_interface] that
        // live inside SpiderMonkey reserved slots.
        let is_allow_unrooted = cx.tcx.has_attrs_with_path(
            item.hir_id().expect_owner(),
            &[
                sym.crown,
                sym.unrooted_must_root_lint,
                sym.allow_unrooted_interior,
            ],
        );
        if !is_allow_unrooted {
            return;
        }

        if let hir::ItemKind::Struct(_, _, variant_data) = &item.kind {
            for field in variant_data.fields() {
                let field_type = cx.tcx.type_of(field.def_id).skip_binder();
                if contains_bare_value(sym, cx, field_type) {
                    cx.lint(BARE_VALUE_IN_GC_STRUCT, |lint| {
                        lint.primary_message(
                            "bare JS::Value in a GC-traced struct must be wrapped in \
                             Heap<Value> (js::heap::Heap<Value>). A bare Value is traced \
                             via TraceNullableRoot (stack-only), which asserts during GC \
                             marking. Heap<Value> uses TraceEdge, which is correct for \
                             heap-resident pointers.",
                        );
                        lint.span(field.span);
                    });
                }
            }
        }
    }
}

symbols! {
    crown
    unrooted_must_root_lint
    allow_unrooted_interior
    jsapi
    JS
    Value
    jsgc
    Heap
}
