[package]
name = "encoding"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
core-runtime.workspace = true
encoding_rs.workspace = true
js.workspace = true
web-streams.workspace = true

[dev-dependencies]
js.workspace = true
libstarling.workspace = true
web-globals.workspace = true
web-streams.workspace = true

[lints]
workspace = true
