[package]
name = "web-globals"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
core-runtime.workspace = true
data-url.workspace = true
encoding_rs.workspace = true
js.workspace = true
url.workspace = true

[dev-dependencies]
libstarling.workspace = true

[lints]
workspace = true
