[package]
name = "core-runtime"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[features]
debugmozjs = ['js/debugmozjs']
jitspew = ['js/jitspew']
profilemozjs = ['js/profilemozjs']

[dependencies]
clap.workspace = true
event-listener.workspace = true
futures-lite = "2"
js.workspace = true
oxc_resolver.workspace = true
shlex = "2"
tempfile = "3"

[lints]
workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio.workspace = true
